Develop (#7)
* improve usage out

and poop YT :)

* improve README.md

most popular language "English" :)

* better

and butter

* improve... improve...

> https://translate.google.com/?sl=en&tl=ja&text=the&op=translate
"the"
3. used to make a generalized reference to something rather than identifying a particular instance.

print *the* download URL
explicit soecify "download URL" is for your typed videoid

I don't understand why writing this...
but I think this makes "download url" is not special thing

* switch to yarn!!

* add jest test

* disable retry for test without error

Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
/home/runner/work/youtube-otosuyatu/youtube-otosuyatu/node_modules/p-cancelable/index.js:48
					throw new Error('The `onCancel` handler was attached after the promise settled.');
           ^
Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/home/runner/work/youtube-otosuyatu/youtube-otosuyatu/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/home/runner/work/youtube-otosuyatu/youtube-otosuyatu/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/home/runner/work/youtube-otosuyatu/youtube-otosuyatu/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:642:26)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at Timeout.retry (/home/runner/work/youtube-otosuyatu/youtube-otosuyatu/node_modules/got/dist/source/core/index.js:1278:30)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)